### ISSUE TITLE
this.currentlyHandled is smaller than 0

### ISSUE THREAD

**Issue by pbartela** [Bartozzz/queue-promise#60]
In dequeue launching Promise.all on empty promises causes negative value on this.currentlyHandled
Because of that the bigger the number of requests the more requests is launched making this.options.concurrent irrelevant

**Comment by Bartozzz** [comment]
I'll have a look at this today and update the library & tests. Thanks for reporting this issue!

**Comment by pbartela** [comment]
Thanks for merging

**Comment by Bartozzz** [comment]
Thanks for your contribution. Should be released in [`queue-promise@1.3.1`](https://www.npmjs.com/package/queue-promise/v/1.3.1). 😄
