### ISSUE TITLE
Queue does not resolve/reject all promises on concurrent execution

### ISSUE THREAD

**Issue by domoran** [Bartozzz/queue-promise#64]
For a simple port scanning script I queued executions of port scans expecting each of the scans to either resolve (port opened) or reject (port closed). 

Another problem I found is that the queue was not really executing concurrently. After analyzing the reason for this I found the problem on the dequeue() method, which is broken in multiple ways: 

`
return Promise.all(promises)
      .then(values => {
        for (let output of values) this.emit("resolve", output);
        return values;#      })
      .catch(error => {
        this.emit("reject", error);
        return error;
      })
      .then(output => {
        this.finalize();
        return output;
      });
`

Promise.all   will reject when the first promise rejects! This has two bad effects: 

1. This leads to finalize only being called once even if multiple promises should have been dequeued, leading the currentlyHandled counter to stay one below max, not allowing concurrent execution anymore but just continue with serial execution 

2. No "reject", "resolve" events will be emitted for the executed tasks, that come after the resolve. 

I will submit a pull request for a fix.

**Comment by Bartozzz** [comment]
@domoran thanks for your PR! I updated a few things and it should be working on [`queue-promise@1.3.2`](https://www.npmjs.com/package/queue-promise/v/1.3.2). Here's the full changelog: https://github.com/Bartozzz/queue-promise/releases/tag/v1.3.2.
